{{- range $name, $app := .Values.applications }}

{{- if $app.enabled }}

apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: {{ $app.name }}
  namespace: {{ $app.namespace }}

spec:

  project: {{ $app.project }}

  source:
    repoURL: {{ $app.repoURL }}
    targetRevision: {{ $app.targetRevision }}
    path: {{ $app.path }}

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true

---

{{- end }}

{{- end }}
