{{- range $name, $repo := .Values.repositories }}

apiVersion: v1
kind: Secret

metadata:
  name: {{ $name }}-repository
  namespace: argocd

  labels:
    argocd.argoproj.io/secret-type: repository

stringData:
  type: {{ $repo.type }}
  url: {{ $repo.url }}

---

{{- end }}
